import Vue from 'vue';
import iView from 'iview';
import VueRouter from 'vue-router';
import axios from 'axios';
import Vuex from 'vuex';
import echarts from 'echarts';
import $ from './libs/weui/js/weui.min';
import weui from './libs/weui/js/weui.min';
import swiper from './libs/swiper/js/swiper.min';